# Generated by Django 2.1.5 on 2019-01-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190111_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='component',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
