# Generated by Django 2.1.5 on 2019-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190119_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.FloatField(default=0.0),
        ),
    ]
