# Generated by Django 2.1.7 on 2019-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
