# Generated by Django 2.1.7 on 2019-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190225_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
